### ISSUE TITLE
Error while setting up profile

### ISSUE THREAD

**Issue by ujjwal04** [benawad/vsinder-app#1]
null is not an object error in login form while setting the city
![Screenshot_2020-12-09-20-52-10-455_com benawad vsinder](https://user-images.githubusercontent.com/43586318/101649755-42176400-3a61-11eb-997a-78ed5d69171d.jpg)

**Comment by eduardomosko** [comment]
Having the same problem. Error screen pops up when I click the location form. Here's my stacktrace:

/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:1722:10476
fr@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:38815
Hr@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:45865
Cl@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:74734
Rl@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:74659
Pl@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:74426
Tl@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:71559
Tl@[native code]
/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:23573
unstable_runWithPriority@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:203:3883
an@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:23520
ln@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:23455
xe@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:89264
Se@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:12420
Re@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:12809
receiveEvent@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:13218
value@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:37:3351
/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:37:748
value@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:37:2611
value@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:37:720
value@[native code]

**Comment by NicestRudeGuy** [comment]
Location got fixed up
