### ISSUE TITLE
Notifications don't work properly

### ISSUE THREAD

**Issue by schuelermine** [benawad/vsinder-app#18]
I got two notifications for two messages sent in a row, and after tapping them, the app opened in a state where the new messages weren't loaded yet (I had been in the relevant chat before the messages arrived).

**Comment by schuelermine** [comment]
I am on Android, and I'm enrolled in the beta

**Comment by benawad** [comment]
I did an over the air update to fix this, try going to the settings and updating the app and let me know if it still persists
