### ISSUE TITLE
Error when uploading code snippet.

### ISSUE THREAD

**Issue by Pablo1107** [benawad/vsinder-app#2]
First this:
![image](https://user-images.githubusercontent.com/17091659/101652482-0ce92280-3a1d-11eb-9163-e5dd75c79cd0.png)

Then this:
![image](https://user-images.githubusercontent.com/17091659/101652502-14103080-3a1d-11eb-8494-426904090551.png)

**Comment by ghost** [comment]
I am having the same issue.
<img width="454" alt="Screen Shot 2020-12-09 at 11 30 47 AM" src="https://user-images.githubusercontent.com/49564726/101657702-30f33680-3a12-11eb-8611-e765d603bea7.png">
