### ISSUE TITLE
App crashes in android while selecting city

### ISSUE THREAD

**Issue by MananDesai54** [benawad/vsinder-app#3]

**Comment by LF-Flores** [comment]
Crashed on Samsung Galaxy A30 with Android 10. stacktrace if needed:

`/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:1722:10476
fr@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:38815
Hr@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:45865
Cl@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:74734
Rl@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:74659
Pl@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:74426
Tl@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:71559
Tl@[native code]
/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:23573
unstable_runWithPriority@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:203:3883
an@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:23520
ln@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:23455
xe@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:89264
Se@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:12420
Re@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:12809
receiveEvent@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:102:13218
value@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:37:3351
/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:37:748
value@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:37:2611
value@/data/user/0/com.benawad.vsinder/files/.expo-internal/bundle-B179276857F8D1631AEBC9BA8AA6F4124D08BBC4362715012831C257F2634107:37:720
value@[native code]`

**Comment by tintin10q** [comment]
I have this issue as well :(

**Comment by MananDesai54** [comment]
yes same for me

**Comment by MananDesai54** [comment]
Now it's working fine foe me, @LF-Flores  what about you?

**Comment by LF-Flores** [comment]
> Now it's working fine foe me, @LF-Flores what about you?

Still the same. I guess i'll just go with the default "online" option in city for the time being

**Comment by MananDesai54** [comment]
okay

**Comment by benawad** [comment]
I did an over the air update for this, so if you close/reopen it'll be fixed

**Comment by MananDesai54** [comment]
Yes mine is updated and created profile successfully, @LF-Flores please confirm so  i close the issue

**Comment by LF-Flores** [comment]
@MananDesai54 Confirmed :) It's fixed for me. Sorry for late reply!
