### ISSUE TITLE
App crashed when selecting city on iPhone

### ISSUE THREAD

**Issue by pdd27673** [benawad/vsinder-app#5]
![B9C3249D-7132-4257-8776-A40A4F003881](https://user-images.githubusercontent.com/60299768/101659832-51fc5d00-39fb-11eb-88e9-e1021b0f8933.png)

Screenshot attached for you to understand it better. Only happens on city select.

**Comment by logangeorge01** [comment]
He said in #3 that he pushed an OTA update that fixes it, you just have to restart the app and it'll work. Not sure if the app checks for OTA updates on download though because I had the same problem and I think I downloaded the app after the update.

**Comment by benawad** [comment]
should be fixed
